### ISSUE TITLE
Updating to 1.9

### ISSUE THREAD

**Issue by Stimulation** [deathmarine/DiabloDrops#104]
Is this plugin dead or will you update it at some point?

**Comment by deathmarine** [comment]
I have no ambition to continue, update or contribute to this plugin. If you would like you can use the source in the creation of a similar or exact copy please respect https://github.com/deathmarine/DiabloDrops/blob/master/license.md

**Comment by Stimulation** [comment]
Okay thank you for the reply, I will indeed!

Take care,

Stimulation
